#!/bin/tcsh

setenv PATH $LCCDIR\:$PATH

set CFLAGS="-Iinclude -D__TCS_V2__ -w"

foreach d (assert ctype errno locale math rt signal stdio stdlib \
	   string time misc)
	foreach f ($d/*.[c])
		lcc $CFLAGS -c `pwd`/$f -Iinclude
	end
end

rm -f libc.a
mips-ar rc libc.a *.o

cp libc.a $LCCDIR
cp -r include/* $LCCDIR/include
rm -f *.o
